### ISSUE TITLE
ConcurrentModificationException 异常

### ISSUE THREAD

**Issue by jxch-1024** [alibaba/transmittable-thread-local#220]
线程池同时运行很多任务的时候会出现这个异常，请问有什么解决办法吗？

```java
java.util.ConcurrentModificationException: null
	at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:806)
	at java.util.WeakHashMap$KeyIterator.next(WeakHashMap.java:839)
	at com.alibaba.ttl.TransmittableThreadLocal$Transmitter.capture(TransmittableThreadLocal.java:287)
	at com.alibaba.ttl.TtlRunnable.<init>(TtlRunnable.java:34)
	at com.alibaba.ttl.TtlRunnable.get(TtlRunnable.java:130)
	at com.alibaba.ttl.TtlRunnable.get(TtlRunnable.java:94)
	at com.alibaba.ttl.threadpool.ExecutorTtlWrapper.execute(ExecutorTtlWrapper.java:27)
```

**Comment by oldratlee** [comment]
首先，确认你使用的是合适的版本（避免废弃有问题的版本），比如使用版本`2.11.5`。
更多说明参见Release note https://github.com/alibaba/transmittable-thread-local/releases 。

@jxch-1024  你用的`TransmittableThreadLocal`库的版本是？ 

给一下更多的环境信息，如`TransmittableThreadLocal`库版本、JDK版本、你的使用方式。

最好能有一个可以运行复现问题的简单Demo：

- 方便排查
- 自然也有复现问题的环境、使用方式等等信息。

**Comment by jxch-1024** [comment]
使用的版本是2.10.2，jdk版本1.8。具体使用情况是多个线程共用同一个线程池，然后均使用这个线程池去执行任务，有概率触发 。

**Comment by jxch-1024** [comment]
很遗憾，在demo中暂时没有复现，真实项目中线程池有嵌套的情况。

**Comment by jxch-1024** [comment]
出现概率比较小，目前换新版本暂时没复现

**Comment by oldratlee** [comment]
@jxch-1024 麻烦还是给一下 可以运行问题Demo（比如 提交成一个 `Github Repo` 我可以查看、分析、运行），
可以展现出 环境、使用方式等等信息，我 可以/想 进一步 分析排查。

PS: `TransmittableThreadLocal`库在并发上尽力做了完备分析与测试，也在线上大规模大流量的使用，库本身出并发问题应该可能性不大。但只要是可能的问题就应该分析看看。

### PS 并发相关的说明与资料

#### 1. [User Guide文档](https://github.com/alibaba/transmittable-thread-local#-user-guide)

> 相比[`InheritableThreadLocal`](https://docs.oracle.com/javase/10/docs/api/java/lang/InheritableThreadLocal.html)，添加了
> 
> 1. `copy`方法  
>     用于定制 **任务提交给线程池时** 的`ThreadLocal`值传递到 **任务执行时** 的拷贝行为，缺省传递的是引用。  
>     注意：如果跨线程传递了对象引用因为不再有线程封闭，与`InheritableThreadLocal.childValue`一样，使用者/业务逻辑要注意传递对象的线程安全。
> 1. `protected`的`beforeExecute`/`afterExecute`方法  

#### 2. TransmittableThreadLocal 是否线程安全 #175 ：

> ### 简单的回答 
> 
> `TransmittableThreadLocal`是线程安全的。 @xingguang2013 
> 
> 对于涉及多线程的库来说（如`ThreadLocal`），缺省要是线程安全，否则就是 _**`BUG`**_。
> （即如不是线程安全，要显式声明出来）
> 
> ### 更完整的回答
> 
> 库的线程安全，是以正确使用为前提，还要加上使用者相关知识的了解，如：
> 
> 
> - 对`ThreadLocal`的了解（这是主题学习）
> - 对线程安全/并发（这是个领域学习）
> 
> 比如 使用`ThreadLocal`时，取出`ThreadLocal`的值（对象引用）并传到其它线程，就要使用者注意额外的线程安全问题了。

#### 3. [`fucking-java-concurrency`](https://github.com/oldratlee/fucking-java-concurrency): 🎏 Simple show cases of java concurrency problems, seeing 🙈 is believing 🐵

**Comment by jxch-1024** [comment]
问题解决了，是由于之前没有使用transmittable-thread-local，为了解决thread-local经常不清理的问题，重写了线程池的afterExecute方法去清理当前线程的threadlocal变量，而现在无需清理。之前清理当前线程的所有threadlocal代码如下：

 /**
     * 清除当前线程的所有ThreadLocal引用
     */
    public static void clearThreadLocal(){
        try {
            final Thread thread = Thread.currentThread();
            final Field threadLocalsField = FieldUtils.getField(Thread.class, "threadLocals", true);
            if (threadLocalsField.get(thread)!=null) {
                threadLocalsField.set(thread,null);
            }
            final Field inheritableThreadLocalsField = FieldUtils.getField(Thread.class, "inheritableThreadLocals", true);
            if(inheritableThreadLocalsField.get(thread)!=null){
                inheritableThreadLocalsField.set(thread,null);
            }
        }catch (Exception e){
            log.error("threadLocal清除失败！",e);
        }
    }
删除即解决了。

**Comment by oldratlee** [comment]
> @jxch-1024 麻烦还是给一下 可以运行问题Demo（比如 提交成一个 `Github Repo` 我可以查看、分析、运行），
> 可以展现出 环境、使用方式等等信息，我 可以/想 进一步 分析排查。

@jxch-1024 欢迎提供进一步信息 与 反馈交流。这个Issue先Close了。 :")

**Comment by imlzw** [comment]
在版本 2.12.2上也会出现，固定出现，在一次事务中多次请求feign接口，第一次feign接口调用会熔断报错；
但神奇的是，单个事务下的接下来多次feign接口正常。每发起一个事务就会出现一次，非常稳定。

升级2.14.4后没有出现问题

```java
java.util.ConcurrentModificationException
at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:806)
at java.util.WeakHashMap$KeyIterator.next(WeakHashMap.java:839)
at com.alibaba.ttl.TransmittableThreadLocal$Transmitter.captureTtlValues(TransmittableThreadLocal.java:409)
at com.alibaba.ttl.TransmittableThreadLocal$Transmitter.capture(TransmittableThreadLocal.java:404)
at com.alibaba.ttl.TtlCallable.<init>(TtlCallable.java:45)
at com.alibaba.ttl.TtlCallable.get(TtlCallable.java:155)
at com.alibaba.ttl.TtlCallable.get(TtlCallable.java:118)
at cn.ffcs.cloudna.openfeign.hystrix.CloudnaHystrixConcurrencyStrategy.wrapCallable(CloudnaHystrixConcurrencyStrategy.java:16)
at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.<init>(HystrixContextRunnable.java:37)
at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator.call(AbstractCommand.java:1138)
at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator.call(AbstractCommand.java:1120)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:44)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10327)
at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.subscribe(Observable.java:10423)
at rx.Observable.subscribe(Observable.java:10390)
at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:51)
at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:410)
at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:378)
at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:344)
at org.springframework.cloud.netflix.hystrix.HystrixCircuitBreaker.run(HystrixCircuitBreaker.java:53)
at org.springframework.cloud.openfeign.FeignCircuitBreakerInvocationHandler.invoke(FeignCircuitBreakerInvocationHandler.java:113)
at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory$1.proceed(FeignCachingInvocationHandlerFactory.java:66)
at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54)
at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:351)
at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory.lambda$create$1(FeignCachingInvocationHandlerFactory.java:53)
at com.sun.proxy.$Proxy284.getToken(Unknown Source)
at cn.ffcs.logcenter.core.utils.InitLoggerTokenUtil.initLoggerToken(InitLoggerTokenUtil.java:59)
at cn.ffcs.logcenter.core.event.listener.LogRecordEventListener.handleLogRecordEvent(LogRecordEventListener.java:92)
at cn.ffcs.logcenter.core.event.listener.LogRecordEventListener$$FastClassBySpringCGLIB$$acefcda0.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at cn.ffcs.logcenter.aspect.MethodLoggerInterceptor.invoke(MethodLoggerInterceptor.java:128)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
at cn.ffcs.logcenter.core.event.listener.LogRecordEventListener$$EnhancerBySpringCGLIB$$30d1a38e.handleLogRecordEvent(<generated>)
at sun.reflect.GeneratedMethodAccessor234.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:429)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:386)
at cn.ffcs.logcenter.core.feign.LoggerClient.loggerMethodFeign(LoggerClient.java:176)
at cn.ffcs.logcenter.core.feign.LoggerClient$$FastClassBySpringCGLIB$$9ce8a877.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
at cn.ffcs.cloudna.web.requestlog.RequestLogAspect.aroundApi(RequestLogAspect.java:85)
at sun.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at cn.ffcs.logcenter.aspect.MethodLoggerInterceptor.invoke(MethodLoggerInterceptor.java:137)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
at cn.ffcs.logcenter.core.feign.LoggerClient$$EnhancerBySpringCGLIB$$7ac19af3.loggerMethodFeign(<generated>)
at sun.reflect.GeneratedMethodAccessor232.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:750)
```

**Comment by jxch-1024** [comment]
已收到您的邮件，祝您生活愉快。
