### ISSUE TITLE
Ttt agent与其他agent兼容性问题

### ISSUE THREAD

**Issue by liauraljl** [alibaba/transmittable-thread-local#226]
最近发现Ttl agent与其他agent共用时，ttlagent必须放在最前面，否则会导致jdk线程池修饰失败，ttl失去作用，比如与SkywalkingAgent、Promethues等共用（未修改agent jar名称）。请问作者有遇到类似问题吗

**Comment by oldratlee** [comment]
确实有其它的同学也反映过这样的问题。 

你方便给一下极简的Demo（在Github建一个Demo Repo） @liauraljl  🙏 ♥️
以运行复现问题，方便我跟进排查，谢谢

**Comment by liauraljl** [comment]
demo：https://github.com/liauraljl/ttl-agent-demo
agent路径：https://github.com/liauraljl/ttl-agent-demo/tree/main/src/main/agentDic
执行结果说明：https://github.com/liauraljl/ttl-agent-demo/blob/main/src/main/agentDic/%E5%90%AF%E5%8A%A8%E5%91%BD%E4%BB%A4%E5%88%86%E6%9E%90%E8%AF%B4%E6%98%8E

**Comment by liauraljl** [comment]
基本定位到问题了：
ttl agent失效是由于在ttl agent之前使用其他agent，导致ThreadPoolExecutor等类在TtlAgent premain执行之前被加载
https://github.com/liauraljl/ttl-agent-demo/blob/main/src/main/agentDic/ThreadPoolExecutor%20%E5%8A%A0%E8%BD%BD.png

https://github.com/liauraljl/ttl-agent-demo/blob/main/src/main/agentDic/TtlAgent%E5%8A%A0%E8%BD%BD.png

最终线程池未被增强：
https://github.com/liauraljl/ttl-agent-demo/blob/main/src/main/agentDic/ttl%20%E5%A2%9E%E5%BC%BA.png

**Comment by liauraljl** [comment]
- 我们目前的解决方案是把Ttl agent放在最前位置，可以保证ttl agent 正常工作，已在开发、测试环境得到验证

- 不过还是希望有更好的解决方案，毕竟人为控制加载顺序的话后续长期迭代难免会出错

**Comment by TuitaKing** [comment]
我觉得这个问题可能有两方面的原因：

- `SkywalkingAgent` 中有`ILog` 这个类，他的初始化是在`TTl agent`之前，如果使用了线程池来打印日志，可能会出现还没有执行`TTl `中的`premain`的时候`Runnable`就已经被加载进去了。导致不成功
- `SkywalkingAgent`中`org.apache.skywalking.apm.agent.core.jvm` 这个包下面包含了很多线程池，这些线程池是`initialDelay=0`的，他的初始化也是优先于`ttl Agent`的。

于是我尝试将`SkywalkingAgent` 中的日志全部切换为 `System.out.println()`，并且去掉`org.apache.skywalking.apm.agent.core.boot.BootService` 文件里的类。做完这两步后通过`arthas`查看加载到`jvm`的类的时候能够看到`TtlRunnable`被顺利加载进去了(开始是看不到`TtlRunnable`这个类的)。而且输出的日志也能证明确实替换成功。
@liauraljl 
 
```java 
 java -javaagent:/Users/tuitaking/source/ttl-agent-demo-main/src/main/agentDic/skywalking/skywalking-agent.jar   -javaagent:/Users/tuitaking/source/ttl-agent-demo-main/src/main/agentDic/ttl/transmittable-thread-local-2.11.5.jar=ttl.agent.logger:STDOUT -jar  ttl-agent-demo-1.0.0-SNAPSHOT.jar
2021-01-11 16:52:03.855 INFO [main] TtlAgent: [TtlAgent.premain] begin, agentArgs: ttl.agent.logger:STDOUT, Instrumentation: sun.instrument.InstrumentationImpl@47af7f3d
2021-01-11 16:52:03.873 INFO [main] TtlTransformer: [TtlTransformer] add Transformlet class com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.TtlExecutorTransformlet success
2021-01-11 16:52:03.874 INFO [main] TtlTransformer: [TtlTransformer] add Transformlet class com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.TtlForkJoinTransformlet success
2021-01-11 16:52:03.874 INFO [main] TtlTransformer: [TtlTransformer] add Transformlet class com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.TtlTimerTaskTransformlet success
2021-01-11 16:52:03.875 INFO [main] TtlAgent: [TtlAgent.premain] addTransformer class com.alibaba.ttl.threadpool.agent.TtlTransformer success
2021-01-11 16:52:03.875 INFO [main] TtlAgent: [TtlAgent.premain] end

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

2021-01-11 16:52:05.231  INFO 27164 --- [           main] c.l.d.t.TtlAgentDemoApplication          : Starting TtlAgentDemoApplication v1.0.0-SNAPSHOT on tuitaking.local with PID 27164 (/Users/tuitaking/source/ttl-agent-demo-main/target/ttl-agent-demo-1.0.0-SNAPSHOT.jar started by tuitaking in /Users/tuitaking/source/ttl-agent-demo-main/target)
2021-01-11 16:52:05.235  INFO 27164 --- [           main] c.l.d.t.TtlAgentDemoApplication          : No active profile set, falling back to default profiles: default
2021-01-11 16:52:06.750  INFO 27164 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-01-11 16:52:06.752 INFO [main] TtlExecutorTransformlet: insert code before method public ScheduledFuture schedule(Runnable, long, TimeUnit) of class java.util.concurrent.ScheduledThreadPoolExecutor: $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-11 16:52:06.769 INFO [main] TtlExecutorTransformlet: insert code before method public ScheduledFuture schedule(Callable, long, TimeUnit) of class java.util.concurrent.ScheduledThreadPoolExecutor: $1 = com.alibaba.ttl.TtlCallable.get($1, false, true);
com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-11 16:52:06.771 INFO [main] TtlExecutorTransformlet: insert code before method public ScheduledFuture scheduleAtFixedRate(Runnable, long, long, TimeUnit) of class java.util.concurrent.ScheduledThreadPoolExecutor: $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-11 16:52:06.773 INFO [main] TtlExecutorTransformlet: insert code before method public ScheduledFuture scheduleWithFixedDelay(Runnable, long, long, TimeUnit) of class java.util.concurrent.ScheduledThreadPoolExecutor: $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-11 16:52:06.774 INFO [main] TtlExecutorTransformlet: insert code before method public void execute(Runnable) of class java.util.concurrent.ScheduledThreadPoolExecutor: $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-11 16:52:06.775 INFO [main] TtlExecutorTransformlet: insert code before method public Future submit(Runnable) of class java.util.concurrent.ScheduledThreadPoolExecutor: $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-11 16:52:06.776 INFO [main] TtlExecutorTransformlet: insert code before method public Future submit(Runnable, Object) of class java.util.concurrent.ScheduledThreadPoolExecutor: $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-11 16:52:06.777 INFO [main] TtlExecutorTransformlet: insert code before method public Future submit(Callable) of class java.util.concurrent.ScheduledThreadPoolExecutor: $1 = com.alibaba.ttl.TtlCallable.get($1, false, true);
com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-11 16:52:06.779 INFO [main] TtlExecutorTransformlet: insert code before method public void execute(Runnable) of class java.util.concurrent.ThreadPoolExecutor: $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-11 16:52:06.782 INFO [main] TtlExecutorTransformlet: insert code before method public boolean remove(Runnable) of class java.util.concurrent.ThreadPoolExecutor: $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
```

**Comment by oldratlee** [comment]
按 @liauraljl 提供的 『demo：https://github.com/liauraljl/ttl-agent-demo 』
走了一遍，确实如你的说的：

把`TTL agent`放在最前位置（如位于`Skywalking Agent`之前），`TTL Agent`的生效的。
否则`Skywalking Agent`在`TTL agent`之前，线程池未被增强（非生效）。

-----------

原因 如 上面 @TuitaKing 的说明，很完整 ♥️  👍  ：

因为`Skywalking Agent`的入口逻辑（`premain `）包含 线程池 的启动，导致 

- 到了`TTL agent`（的`premain`）时，`TTL`需要加强的线程池类已经加载（`load`）了。
- 而`TTL`的`TtlTransformer`是在类加载时增强；如果类已经加载了会跳过增加逻辑。

感谢 @TuitaKing 的精彩分析与排查～～

----------


> Quote from @liauraljl 
>
> ### 我们目前的解决方案是
> 把`TTL agent`放在最前位置，可以保证`TTL agent` 正常工作。
> 已在开发、测试环境得到验证。

**_COOL_**！

**Comment by oldratlee** [comment]
> Quote from @liauraljl
>
> 不过还是希望有更好的解决方案，
> 毕竟人为控制 **_`Agent`加载顺序_** 的话后续长期迭代难免会出错。

我试着解决 **_`Agent`加载顺序_**：

- 实验的修改在[分支`expt/fix-agent-order-problem`](https://github.com/alibaba/transmittable-thread-local/tree/expt/fix-agent-order-problem)：
- 修改逻辑是：加载`TtlAgent`时，`retransform`已加载的类： https://github.com/alibaba/transmittable-thread-local/commit/d8cd603008c951c5f4c7e82f7eb3f866d41c9423#diff-7baf52d90b056f08a33f25f27d6df84ecd50797196db42bc39b984f57ccceb2eR147-R156

使用这个`TTL`分支的`TTL Jar`，运行 @liauraljl 的 `ttl-agent-demo`：

- 会出`java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces`
- 即不允许`retransform`类`ScheduledThreadPoolExecutor`
- （Java启动参数 与 运行输出日志 附在 文后）





------------

Java启动参数：

```bash
java \
    -javaagent:src/main/agentdic/skywalking/skywalking-agent.jar \
    -javaagent:path/to/ttl/target/transmittable-thread-local-2.13.0-SNAPSHOT.jar=ttl.agent.logger:stdout \
    -jar target/ttl-agent-demo-1.0.0-SNAPSHOT.jar
```
 
运行输出日志：

```java
......
2021-01-18 00:26:13.408 INFO [main] TtlAgent: retransform class: class java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue
2021-01-18 00:26:13.422 INFO [main] TtlAgent: retransform class: class java.util.concurrent.ThreadPoolExecutor$AbortPolicy
2021-01-18 00:26:13.434 INFO [main] TtlAgent: retransform class: class java.util.concurrent.ScheduledThreadPoolExecutor
2021-01-18 00:26:13.438 INFO [main] TtlExecutorTransformlet: insert code before method public ScheduledFuture scheduleAtFixedRate(Runnable, long, long, TimeUnit) of class java.util.concurrent.ScheduledThreadPoolExecutor:
    $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
    com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
......
2021-01-18 00:26:13.460 INFO [main] TtlExecutorTransformlet: insert code before method public void execute(Runnable) of class java.util.concurrent.ScheduledThreadPoolExecutor:
    $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
    com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
2021-01-18 00:26:13.462 SEVERE [main] TtlAgent: Fail to load TtlAgent , cause: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
        at com.alibaba.ttl.threadpool.agent.TtlAgent.premain(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.IllegalStateException: Fail to load TtlAgent , cause: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
        at com.alibaba.ttl.threadpool.agent.TtlAgent.premain(Unknown Source)
        ... 6 more
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
        at com.alibaba.ttl.threadpool.agent.TtlAgent.premain(Unknown Source)
        ... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
[1]    68385 abort      java -javaagent:src/main/agentdic/skywalking/skywalking-agent.jar  -jar
```

**Comment by oldratlee** [comment]
@liauraljl  @TuitaKing  README文档中 增加一个FAQ：

> ### 1. `TTL Agent`与其它`Agent`（如`Skywalking`、`Promethues`）配合使用时不生效？
> https://github.com/alibaba/transmittable-thread-local#-faq

**Comment by TuitaKing** [comment]
@oldratlee 这个错(`class redefinition failed: attempted to change superclass or interfaces`)是因为[RetransformClasses](https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#RetransformClasses)方法的限制，不能增加、删除、和修改方法签名，或者修饰符，还有继承关系。我`debug`了`openjdk`排查了下，在`~source/openjdk-jdk8u/hotspot/src/share/vm/prims/jvmtiRedefineClasses.cpp`中会有一个`compare_and_normalize_class_versions` 方法中的`n_intfs != k_new_interfaces->length()` 判断抛出该异常，即修改前后的接口数量不一致，违反了上面不能修改继承关系的规则。具体原因应该是`TtlAgent`中让每个被包装的线程池都实现了`TtlAgentEnhanced`，这个是用来避免父类再被包装？我去掉这个实现该接口的逻辑，发现是可以做到的且。但是仅仅只是用来测试和学习。后面是`arthas`反编译后的部分代码，还有启动的日志。

----

`-javaagent:/Users/tuitaking/source/ttl-agent-demo-main/src/main/agentDic/skywalking/skywalking-agent.jar
-javaagent:/Users/tuitaking/source/transmittable-thread-local/target/transmittable-thread-local-2.13.0-SNAPSHOT.jar=ttl.agent.logger:STDOUT
-jar
/Users/tuitaking/source/ttl-agent-demo-main/target/ttl-agent-demo-1.0.0-SNAPSHOT.jar`

----
反编译：

```java 
public class ScheduledThreadPoolExecutor extends ThreadPoolExecutor implements ScheduledExecutorService {
    private volatile boolean continueExistingPeriodicTasksAfterShutdown;
    private volatile boolean executeExistingDelayedTasksAfterShutdown = true;
    private volatile boolean removeOnCancel = false;
    private static final AtomicLong sequencer = new AtomicLong();

    public ScheduledThreadPoolExecutor(int corePoolSize) {
        super(corePoolSize, 2147483647, 0L, TimeUnit.NANOSECONDS, new java.util.concurrent.ScheduledThreadPoolExecutor.DelayedWorkQueue());
    }

    public ScheduledThreadPoolExecutor(int corePoolSize, ThreadFactory threadFactory) {
        super(corePoolSize, 2147483647, 0L, TimeUnit.NANOSECONDS, new java.util.concurrent.ScheduledThreadPoolExecutor.DelayedWorkQueue(), threadFactory);
    }

    public ScheduledThreadPoolExecutor(int corePoolSize, RejectedExecutionHandler handler) {
        super(corePoolSize, 2147483647, 0L, TimeUnit.NANOSECONDS, new java.util.concurrent.ScheduledThreadPoolExecutor.DelayedWorkQueue(), handler);
    }

    public ScheduledThreadPoolExecutor(int corePoolSize, ThreadFactory threadFactory, RejectedExecutionHandler handler) {
        super(corePoolSize, 2147483647, 0L, TimeUnit.NANOSECONDS, new java.util.concurrent.ScheduledThreadPoolExecutor.DelayedWorkQueue(), threadFactory, handler);
    }

    public void shutdown() {
        super.shutdown();
    }

    public void execute(Runnable command) {
        Runnable command = TtlRunnable.get(command, false, true);
        Utils.setAutoWrapperAttachment(command);
        this.schedule((Runnable)command, 0L, TimeUnit.NANOSECONDS);
    }
.......

```
-------

日志

```java

DEBUG 2021-02-02 18:14:15:209 main AgentPackagePath : The beacon class location is jar:file:/Users/tuitaking/source/ttl-agent-demo-main/src/main/agentDic/skywalking/skywalking-agent.jar!/org/apache/skywalking/apm/agent/core/boot/AgentPackagePath.class. 
2021-02-02 18:14:16.232 INFO [main] TtlAgent: [TtlAgent.premain] begin, agentArgs: ttl.agent.logger:STDOUT, Instrumentation: sun.instrument.InstrumentationImpl@776aec5c
2021-02-02 18:14:16.290 INFO [main] TtlTransformer: [TtlTransformer] add Transformlet class com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.TtlExecutorTransformlet success
2021-02-02 18:14:16.291 INFO [main] TtlAgent: [TtlAgent.premain] addTransformer class com.alibaba.ttl.threadpool.agent.TtlTransformer success
2021-02-02 18:14:16.292 INFO [main] TtlAgent: [TtlAgent.premain] end
2021-02-02 18:14:16.324 INFO [main] TtlAgent: retransform class: class java.util.concurrent.ThreadPoolExecutor
2021-02-02 18:14:16.361 INFO [main] TtlExecutorTransformlet: insert code before method public void execute(Runnable) of class java.util.concurrent.ThreadPoolExecutor:
    $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
    com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

2021-02-02 18:14:21.281  INFO 70498 --- [           main] c.l.d.t.TtlAgentDemoApplication          : Starting TtlAgentDemoApplication v1.0.0-SNAPSHOT on tuitaking.local with PID 70498 (/Users/tuitaking/source/ttl-agent-demo-main/target/ttl-agent-demo-1.0.0-SNAPSHOT.jar started by tuitaking in /Users/tuitaking/source/openjdk-jdk8u/build/macosx-x86_64-normal-server-slowdebug/jdk/bin)
2021-02-02 18:14:21.309  INFO 70498 --- [           main] c.l.d.t.TtlAgentDemoApplication          : No active profile set, falling back to default profiles: default
2021-02-02 18:14:32.302  INFO 70498 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-02-02 18:14:32.527  INFO 70498 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-02-02 18:14:32.528  INFO 70498 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.16]
2021-02-02 18:14:32.616  INFO 70498 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/tuitaking/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2021-02-02 18:14:33.309  INFO 70498 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-02-02 18:14:33.310  INFO 70498 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 11551 ms
2021-02-02 18:14:35.244  INFO 70498 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-02-02 18:14:37.218  INFO 70498 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-02-02 18:14:37.250  INFO 70498 --- [           main] c.l.d.t.TtlAgentDemoApplication          : Started TtlAgentDemoApplication in 18.986 seconds (JVM running for 23.442)
2021-02-02 18:15:02.917 INFO [arthas-command-execute] TtlExecutorTransformlet: insert code before method public void execute(Runnable) of class java.util.concurrent.ScheduledThreadPoolExecutor:
    $1 = com.alibaba.ttl.TtlRunnable.get($1, false, true);
    com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.setAutoWrapperAttachment($1);
```

**Comment by oldratlee** [comment]
> 这个错(`class redefinition failed: attempted to change superclass or interfaces`)
> 是因为[`RetransformClasses`](https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#RetransformClasses)方法的限制：不能增加、删除、和修改方法签名，或者修饰符，还有继承关系。
> 
> 具体原因应该是`TtlAgent`中让每个被包装的线程池都实现了`TtlAgentEnhanced`。
>  我去掉这个实现该接口的逻辑，发现是可以做到的。

COOL! 👍 ♥️  @TuitaKing 

> 这个是用来避免父类再被包装？

目前只是用来语义标识。

**Comment by oldratlee** [comment]
@TuitaKing 看你非常了解`Java Agent` 与 TTL的整个过程与实现 👍

你有没有兴趣 或 方便有空 来实现一下，TTL的加载后类修改增强的功能？（`ForkJoinPool` 的实现可能有些复杂） @TuitaKing 😁 ❤️

**Comment by TuitaKing** [comment]
我可以尝试下😁。不过我还处于学习状态，可能花的时间比较久，尽力而为🙏。

**Comment by TuitaKing** [comment]
我尝试了几次修改已经加载的class。但是RetransformClasses的限制又点多，会去掉TTL很多设计，比如都实现相同的接口 这类设计。所以我觉得暂时只能使用规范规范话的使用下。后续会使用bytebuddy进行尝试，但是和现在的设计区别较大。望知晓。有点抱歉

**Comment by oldratlee** [comment]
> 我尝试了几次修改已经加载的class。
> 
> 但是`RetransformClasses`的限制又点多，会去掉`TTL`比如都实现相同的接口这类设计。
> 所以我觉得暂时只能使用规范（`TTL`在前）来避开上面的问题。
> 
> 后续我会使用`bytebuddy`进行尝试，但是和现在的设计区别较大。
> 
> 望知晓。有点抱歉

收到。辛苦了～ ♥️
期望ing～
