### ISSUE TITLE
TTL Agent的使用方式下，PriorityBlockingQueue（非PriorityBlockingQueue<Runnable>）抛出ClassCastException

### ISSUE THREAD

**Issue by fzdwx** [alibaba/transmittable-thread-local#361]
就是powerjob worker（应用）启动的时候会初始化一个h2数据库

![image](https://user-images.githubusercontent.com/65269574/157151363-da404c7b-fbbc-4084-add9-969313f5a47d.png)
![image](https://user-images.githubusercontent.com/65269574/157151466-a2c6c4a6-45ef-4557-8769-f92e1c4064be.png)
![image](https://user-images.githubusercontent.com/65269574/157151482-524ef689-62ba-4f30-9807-37bafb93adc6.png)

### 具体报错

```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initPowerJob' defined in class path resource [tech/powerjob/worker/autoconfigure/PowerJobAutoConfiguration.class]: Invocation of init method failed; nested exception is org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database has been closed [90098-200]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:445)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at com.huofutp.HfScrmSysApplication.main(HfScrmSysApplication.java:25)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database has been closed [90098-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.engine.Session.getTransaction(Session.java:1792)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1804)
	at org.h2.engine.Session.setSavepoint(Session.java:915)
	at org.h2.command.Command.executeUpdate(Command.java:244)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at tech.powerjob.worker.persistence.TaskDAOImpl.initTable(TaskDAOImpl.java:34)
	at tech.powerjob.worker.persistence.TaskPersistenceService.init(TaskPersistenceService.java:48)
	at tech.powerjob.worker.PowerJobWorker.init(PowerJobWorker.java:140)
	at tech.powerjob.worker.PowerJobWorker.afterPropertiesSet(PowerJobWorker.java:67)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 16 common frames omitted
Caused by: java.lang.IllegalStateException: java.lang.ClassCastException: org.h2.mvstore.MVStore$RemovedPageInfo cannot be cast to java.lang.Runnable [1.4.200/3]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.MVStore.store(MVStore.java:1338)
	at org.h2.mvstore.MVStore.store(MVStore.java:1312)
	at org.h2.mvstore.MVStore.tryCommit(MVStore.java:1272)
	at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2780)
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3290)
Caused by: java.lang.ClassCastException: org.h2.mvstore.MVStore$RemovedPageInfo cannot be cast to java.lang.Runnable
	at com.alibaba.ttl.threadpool.TtlRunnableUnwrapComparator.compare(TtlRunnableUnwrapComparator.java:15)
	at java.util.concurrent.PriorityBlockingQueue.siftUpUsingComparator(PriorityBlockingQueue.java:374)
	at java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:491)
	at java.util.concurrent.PriorityBlockingQueue.add(PriorityBlockingQueue.java:463)
	at org.h2.mvstore.MVStore.accountForRemovedPage(MVStore.java:2237)
	at org.h2.mvstore.Page.removePage(Page.java:861)
	at org.h2.mvstore.CursorPos.processRemovalInfo(CursorPos.java:72)
	at org.h2.mvstore.MVMap.operate(MVMap.java:1909)
	at org.h2.mvstore.MVMap.put(MVMap.java:151)
	at org.h2.mvstore.MVStore.storeNow(MVStore.java:1366)
	at org.h2.mvstore.MVStore.store(MVStore.java:1334)
	... 4 common frames omitted
```

请问有没有办法排除这个？或者您有没有更好的解决办法。。。

**Comment by fzdwx** [comment]
2.就为什么我再主线程中remove了，但是其他的线程还是能获取到值？并且这个线程还是一个早就启动了的线程，比如说rocketmq中的RocketmqRemoting
![8CFF200C-24FC-4d0f-BF62-868C4FD98660(1)](https://user-images.githubusercontent.com/65269574/157158108-88d81654-8a1e-4d82-b73f-f3022c84902f.png)

**Comment by fzdwx** [comment]
用了agent包装还是这样...

**Comment by fzdwx** [comment]
就是存入一次context后，其他任意线程都能获取到，然后`remove`之后，`set`的线程获取不到，其他线程还是能获取到
![image](https://user-images.githubusercontent.com/65269574/157162211-56053959-d888-4b52-80af-984af6816592.png)

![image](https://user-images.githubusercontent.com/65269574/157162461-d6cb309a-cf92-414e-82d5-ca8cbb6a759d.png)

**Comment by fzdwx** [comment]
我是不是哪里用的姿势不对 😭

**Comment by oldratlee** [comment]
@fzdwx `PriorityBlockingQueue`相关的问题。

给一个可以说明/复现问题的、极简可运行的Demo工程 ❤️；推荐：

- 提交成一个`github repo`，方便大家运行以了解、重现问题与排查解决
- 就像这个Issue https://github.com/alibaba/transmittable-thread-local/issues/226#issuecomment-739314037 给的工程 [`liauraljl/ttl-agent-demo`](https://github.com/liauraljl/ttl-agent-demo)

有一个可以说明/复现问题的、极简可运行的Demo工程，也可以排除可能的使用上的问题。

### 相关 Issue

- #330
- #178

**Comment by oldratlee** [comment]
@fzdwx 问题已经确定了，正在修改中。

发一个版本出来后，你可以用新版本测试一下。

**Comment by oldratlee** [comment]
发布了 `v2.12.5` @fzdwx 
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.5

试一下 看看解决你的问题

**Comment by oldratlee** [comment]
> 2.就为什么我再主线程中remove了，但是其他的线程还是能获取到值？并且这个线程还是一个早就启动了的线程，比如说rocketmq中的RocketmqRemoting
> 就是存入一次context后，其他任意线程都能获取到，然后remove之后，set的线程获取不到，其他线程还是能获取到

对于第二问题，和 使用方式与逻辑流程相关，可能涉及很多组件。
不能简单看看给你反馈。

你提供了 一个可以复现问题的、极简可运行的Demo工程 后，
可以开一下独立Issue 跟进。 @fzdwx

**Comment by fzdwx** [comment]
ok,收到，我测试一下第一个问题，稍后给您答复。

**Comment by fzdwx** [comment]
复现了。。我马上提一个新的issue @oldratlee
