### ISSUE TITLE
通过agent方式做字节码增强引起ClassLoader.loadClass加载Narhon引擎时报错Nest-host class_info_index 21 has bad constant type

### ISSUE THREAD

**Issue by howardliu-cn** [alibaba/transmittable-thread-local#388]
启动参数：-javaagent:transmittable-thread-local-2.12.1.jar

运行时报错：Caused by: java.lang.ClassFormatError: Nest-host class_info_index 21 has bad constant type in class file jdk/nashorn/internal/codegen/OptimisticTypesPersistence$5

代码：
```java
        ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine engine = manager.getEngineByName("JavaScript");
        Object result = engine.eval(formula);
``` 

异常栈:
```log
Caused by: java.lang.ClassFormatError: Nest-host class_info_index 21 has bad constant type in class file jdk/nashorn/internal/codegen/OptimisticTypesPersistence$5
        at java.base/java.lang.ClassLoader.defineClass2(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:759)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:680)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:605)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.RecompilableScriptFunctionData.getCompiler(RecompilableScriptFunctionData.java:669)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.RecompilableScriptFunctionData.getCompiler(RecompilableScriptFunctionData.java:650)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.RecompilableScriptFunctionData.compileTypeSpecialization(RecompilableScriptFunctionData.java:726)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.RecompilableScriptFunctionData.getBest(RecompilableScriptFunctionData.java:907)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.getGeneric(ScriptFunctionData.java:402)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.createGenericInvoker(ScriptFunctionData.java:297)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.getGenericInvoker(ScriptFunctionData.java:291)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
```

删除这个agent就能够表现正常。

**Comment by oldratlee** [comment]
搜索了一下，应该要升级`javassist`。

@howardliu-cn 你可以

- 升级`java`到 8
- 升级`javassist`到最新版本

打个`TTL`包试一下能不能解决问题，

如果 OK，我发布个`TTL`新版本出来。

**Comment by oldratlee** [comment]
@howardliu-cn 发布了`v2.13.0`，试一下

``` xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>transmittable-thread-local</artifactId>
    <version>2.13.0</version>
</dependency>
```

Release Note:
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.13.0

**Comment by oldratlee** [comment]
@howardliu-cn 先 close 了。有问题继续讨论 ❤️

**Comment by howardliu-cn** [comment]
多谢，线下环境已验证可行，今晚线上环境验证一下。

**Comment by howardliu-cn** [comment]
已在线上验证，可行
