### ISSUE TITLE
jdk11 报错。

### ISSUE THREAD

**Issue by zhuyixiang** [alibaba/transmittable-thread-local#505]
你好，我的应用使用jdk11，报错误。

```java
java.io.IOException: invalid constant type: 17 at 103
official
2023-05-16 07:14:00.595
at com.alibaba.ttl.threadpool.agent.transformlet.javassist.bytecode.ClassFile.read(ClassFile.java:794)
official
2023-05-16 07:14:00.595
at com.alibaba.ttl.threadpool.agent.transformlet.helper.AbstractExecutorTtlTransformlet.doTransform(AbstractExecutorTtlTransformlet.java:63)
official
2023-05-16 07:14:00.595
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
```

请问如何解决

**Comment by oldratlee** [comment]
@zhuyixiang 说明

- 相关的环境：如使用`TTL`的版本。
   - 是最新版本吗？
- 一个可以运行复现问题的极简demo

**Comment by zhuyixiang** [comment]
我准备升级到最新版本，能顺利支持jdk11 吗

**Comment by zhuyixiang** [comment]
之前用的是2.13

**Comment by oldratlee** [comment]
> 支持jdk11 吗

支持的。
