### ISSUE TITLE
agent方式使用TTL，jdk从8升到11之后项目启动报错 类重复加载： java.lang.LinkageError: loader java.net.URLClassLoader attempted duplicate class

### ISSUE THREAD

**Issue by JiaYao9701** [alibaba/transmittable-thread-local#518]
完整报错如下：

```java
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.taobao.pandora.boot.loader.SarLoaderUtils.invokeStart(SarLoaderUtils.java:258)
	at com.taobao.pandora.boot.loader.SarLoaderUtils.getClassCache(SarLoaderUtils.java:216)
	at com.taobao.pandora.boot.loader.SarLauncher.loadSar(SarLauncher.java:92)
	at com.taobao.pandora.boot.loader.SarLauncher.createClassLoader(SarLauncher.java:64)
	at com.taobao.pandora.boot.loader.Launcher.createClassLoader(Launcher.java:64)
	at com.taobao.pandora.boot.loader.Launcher.launch(Launcher.java:49)
	at com.taobao.pandora.boot.loader.SarLauncher.main(SarLauncher.java:171)
Caused by: java.lang.RuntimeException: com.taobao.pandora.common.exception.PandoraException: java.lang.LinkageError: loader java.net.URLClassLoader @3098cf3b attempted duplicate class definition for com.taobao.pandora.loader.jar.JarURLConnection$1. (com.taobao.pandora.loader.jar.JarURLConnection$1 is in unnamed module of loader java.net.URLClassLoader @3098cf3b, parent loader 'platform')
	at com.taobao.pandora.service.pipeline.Pipeline.execute(Pipeline.java:83)
	at com.taobao.pandora.PandoraContainer.start(PandoraContainer.java:142)
	... 11 more
Caused by: com.taobao.pandora.common.exception.PandoraException: java.lang.LinkageError: loader java.net.URLClassLoader @3098cf3b attempted duplicate class definition for com.taobao.pandora.loader.jar.JarURLConnection$1. (com.taobao.pandora.loader.jar.JarURLConnection$1 is in unnamed module of loader java.net.URLClassLoader @3098cf3b, parent loader 'platform')
	at com.taobao.pandora.service.initializer.InitializerChecker.checkModule(InitializerChecker.java:80)
	at com.taobao.pandora.stage.InitializerCheck.stepIn(InitializerCheck.java:35)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:86)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.Pipeline.execute(Pipeline.java:78)
	... 12 more
Caused by: java.lang.LinkageError: loader java.net.URLClassLoader @3098cf3b attempted duplicate class definition for com.taobao.pandora.loader.jar.JarURLConnection$1. (com.taobao.pandora.loader.jar.JarURLConnection$1 is in unnamed module of loader java.net.URLClassLoader @3098cf3b, parent loader 'platform')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1133)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClassInternal(URLClassLoader.java:648)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:573)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:477)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:464)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClassInternal(URLClassLoader.java:463)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:455)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:626)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:558)
	at com.taobao.pandora.loader.jar.Handler.setUseFastConnectionExceptions(Handler.java:308)
	at com.taobao.pandora.service.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:73)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:558)
	at com.taobao.pandora.service.initializer.InitializerChecker.checkModule(InitializerChecker.java:75)
```

通过打印每个类被`define`时的线程调用栈，发现是`TTL`的问题：

- 启动时加载`JarURLConnection$1`这个类，进入`TTL`的`transform`流程；
- 在`TTL`的`transform`流程中，会使用`ContextClassLoader`执行`getResource`方法，
  - 这此时的`ContextClassLoader`是`pandora`的`MoudleClassLoader`；
- `pandora MoudleClassLoader`的`getResource`方法又会去加载`JarURLConnection$1`这个类
- 于是出现了类重复定义异常

想问下大佬有没有什么好的解决方案

**Comment by oldratlee** [comment]
@JiaYao9701 照着你的说明，我也理了一遍前后的流程：

1. `pandora.ModuleClassLoader` load classes
    - _`pandora.ModuleClassLoader` need class `pandora.JarURLConnection$1`_
2. load class `pandora.JarURLConnection$1`(first) 🏋️‍♀️
3. tigger `TTL Transformer` when loading class `pandora.JarURLConnection$1`
    - _`TTL Transformer` need load class files by class loader(`pandora.ModuleClassLoader`)_
    - _`pandora.ModuleClassLoader` need class `pandora.JarURLConnection$1`_
    - _but class `pandora.JarURLConnection$1` is loading/**not completed**_
    - so load it(again「叕」) 🏋️‍♀️ 
    - ==> cause `LinkageError: attempted duplicate class definition` 💥

-------------

因为类加载会触发`(TTL) Transformer`，这个应该不能控制跳过（由`Java Agent`机制决定）。

所以一个做法是，需要配置`TTL Transformer`可以跳过哪些类的`transform`。 @JiaYao9701 

`TTL Transformer`已经有一些跳过`transform`：

https://github.com/alibaba/transmittable-thread-local/blob/4655ffc1168e249c534097e0d251a1f4faf487c1/src/main/java/com/alibaba/ttl/threadpool/agent/TtlTransformer.java#L49-L57

功能：`TTL Transformer`支持配置以跳过指定类或包的`transform`。
这个我思考然后实现一下。

-------------

@JiaYao9701 对于你这个的具体问题，快速的解决方案 是 新加跳过判断，比如：

```diff
     final String className = toClassName(classFile);
     if (isClassUnderPackage(className, "com.alibaba.ttl")) return NO_TRANSFORM;
     if (isClassUnderPackage(className, "java.lang")) return NO_TRANSFORM;
+    if (isClassUnderPackage(className, "com.taobao.pandora.loader")) return NO_TRANSFORM;
```

你可以修改后，自己打个包先快速安全的解决问题 💕 @JiaYao9701

**Comment by JiaYao9701** [comment]
按照这个方式：
```
final String className = toClassName(classFile);
     if (isClassUnderPackage(className, "com.alibaba.ttl")) return NO_TRANSFORM;
     if (isClassUnderPackage(className, "java.lang")) return NO_TRANSFORM;
+    if (isClassUnderPackage(className, "com.taobao.pandora.loader")) return NO_TRANSFORM;
+    if (isClassUnderPackage(className, "com.taobao.pandora.service.loader")) return NO_TRANSFORM;
```
我将`TTL 2.14.2`重新打包并且验证了一下，出现了新的问题：
```
2023-06-15 15:46:29.713 SEVERE [main] TtlTransformer: Fail to transform class com/taobao/spas/sdk/common/cache/ConcurrentLRUCache$1, cause: com.alibaba.ttl.threadpool.agent.internal.javassist.CannotCompileException: [source error] no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
com.alibaba.ttl.threadpool.agent.internal.javassist.CannotCompileException: [source error] no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtBehavior.setBody(CtBehavior.java:474)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtBehavior.setBody(CtBehavior.java:440)
	at com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.doTryFinallyForMethod(Utils.java:89)
	at com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.doTryFinallyForMethod(Utils.java:61)
	at com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.TtlTimerTaskTransformlet.updateTimerTaskClass(TtlTimerTaskTransformlet.java:75)
	at com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.TtlTimerTaskTransformlet.doTransform(TtlTimerTaskTransformlet.java:54)
	at com.alibaba.ttl.threadpool.agent.TtlTransformer.transform(TtlTransformer.java:64)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1133)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClassInternal(URLClassLoader.java:665)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:593)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:477)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:464)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClassInternal(URLClassLoader.java:463)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:455)
	at com.taobao.pandora.service.loader.ModuleClassLoader.resolveClassPath(ModuleClassLoader.java:289)
	at com.taobao.pandora.service.loader.ModuleClassLoader.loadClassInternal(ModuleClassLoader.java:126)
	at com.taobao.pandora.service.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:558)
	at com.taobao.pandora.service.sharedclass.ClassExporter.scanFromExportIndex(ClassExporter.java:151)
	at com.taobao.pandora.service.sharedclass.ClassExporter.exportClasses(ClassExporter.java:76)
	at com.taobao.pandora.stage.ExportClass2Cache.stepIn(ExportClass2Cache.java:30)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:86)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.Pipeline.execute(Pipeline.java:78)
	at com.taobao.pandora.PandoraContainer.start(PandoraContainer.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.taobao.pandora.boot.loader.SarLoaderUtils.invokeStart(SarLoaderUtils.java:258)
	at com.taobao.pandora.boot.loader.SarLoaderUtils.getClassCache(SarLoaderUtils.java:216)
	at com.taobao.pandora.boot.loader.SarLauncher.loadSar(SarLauncher.java:92)
	at com.taobao.pandora.boot.loader.SarLauncher.createClassLoader(SarLauncher.java:64)
	at com.taobao.pandora.boot.loader.Launcher.createClassLoader(Launcher.java:64)
	at com.taobao.pandora.boot.loader.Launcher.launch(Launcher.java:49)
	at com.taobao.pandora.boot.loader.SarLauncher.main(SarLauncher.java:171)
Caused by: compile error: no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.MemberResolver.searchImports(MemberResolver.java:479)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:422)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:329)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:711)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.atDeclarator(CodeGen.java:819)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.ast.Declarator.accept(Declarator.java:103)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.Javac.compileBody(Javac.java:228)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtBehavior.setBody(CtBehavior.java:466)
	... 44 more
2023-06-15 15:46:29.812 SEVERE [main] TtlTransformer: Fail to transform class com/taobao/vipserver/client/backups/FailoverReactor$DiskFileWriter, cause: com.alibaba.ttl.threadpool.agent.internal.javassist.CannotCompileException: [source error] no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
com.alibaba.ttl.threadpool.agent.internal.javassist.CannotCompileException: [source error] no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtBehavior.setBody(CtBehavior.java:474)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtBehavior.setBody(CtBehavior.java:440)
	at com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.doTryFinallyForMethod(Utils.java:89)
	at com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.Utils.doTryFinallyForMethod(Utils.java:61)
	at com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.TtlTimerTaskTransformlet.updateTimerTaskClass(TtlTimerTaskTransformlet.java:75)
	at com.alibaba.ttl.threadpool.agent.internal.transformlet.impl.TtlTimerTaskTransformlet.doTransform(TtlTimerTaskTransformlet.java:54)
	at com.alibaba.ttl.threadpool.agent.TtlTransformer.transform(TtlTransformer.java:64)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1133)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClassInternal(URLClassLoader.java:665)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:593)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:477)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:464)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClassInternal(URLClassLoader.java:463)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:455)
	at com.taobao.pandora.service.loader.ModuleClassLoader.resolveClassPath(ModuleClassLoader.java:289)
	at com.taobao.pandora.service.loader.ModuleClassLoader.loadClassInternal(ModuleClassLoader.java:126)
	at com.taobao.pandora.service.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:558)
	at com.taobao.pandora.service.sharedclass.ClassExporter.scanFromExportIndex(ClassExporter.java:151)
	at com.taobao.pandora.service.sharedclass.ClassExporter.exportClasses(ClassExporter.java:76)
	at com.taobao.pandora.stage.ExportClass2Cache.stepIn(ExportClass2Cache.java:30)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:86)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.StageNode.stepIn(StageNode.java:90)
	at com.taobao.pandora.service.pipeline.Pipeline.execute(Pipeline.java:78)
	at com.taobao.pandora.PandoraContainer.start(PandoraContainer.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.taobao.pandora.boot.loader.SarLoaderUtils.invokeStart(SarLoaderUtils.java:258)
	at com.taobao.pandora.boot.loader.SarLoaderUtils.getClassCache(SarLoaderUtils.java:216)
	at com.taobao.pandora.boot.loader.SarLauncher.loadSar(SarLauncher.java:92)
	at com.taobao.pandora.boot.loader.SarLauncher.createClassLoader(SarLauncher.java:64)
	at com.taobao.pandora.boot.loader.Launcher.createClassLoader(Launcher.java:64)
	at com.taobao.pandora.boot.loader.Launcher.launch(Launcher.java:49)
	at com.taobao.pandora.boot.loader.SarLauncher.main(SarLauncher.java:171)
Caused by: compile error: no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.MemberResolver.searchImports(MemberResolver.java:479)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:422)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:329)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:711)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.atDeclarator(CodeGen.java:819)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.ast.Declarator.accept(Declarator.java:103)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.compiler.Javac.compileBody(Javac.java:228)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtBehavior.setBody(CtBehavior.java:466)
	... 44 more
2023-06-15 15:46:29.879 SEVERE [main] TtlTransformer: Fail to transform class com/taobao/diamond/identify/CredentialWatcher$1, cause: com.alibaba.ttl.threadpool.agent.internal.javassist.CannotCompileException: [source error] no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
com.alibaba.ttl.threadpool.agent.internal.javassist.CannotCompileException: [source error] no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtBehavior.setBody(CtBehavior.java:474)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtBehavior.setBody(CtBehavior.java:440)
```
目前还不知道原因，正在排查-_-

**Comment by oldratlee** [comment]
`no such class`，看起来是`Classloader`及其代理关系的设置问题，应该与`TTL`没有关系了。 

这个 issue 先 close。

```java
2023-06-15 15:46:29.879 SEVERE [main] TtlTransformer: Fail to transform class com/taobao/diamond/identify/CredentialWatcher$1, cause: com.alibaba.ttl.threadpool.agent.internal.javassist.CannotCompileException: [source error] no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
com.alibaba.ttl.threadpool.agent.internal.javassist.CannotCompileException: [source error] no such class: com.alibaba.ttl.TransmittableThreadLocal.Transmitter
```

**Comment by Truquer** [comment]
我们在JDK8升级17的过程中，微服务启动也遇到了类似的问题，请问会大佬会出版本支持配置跳过哪些类的transform吗
