### ISSUE TITLE
java.lang.IllegalStateException: TTL logger implementation type is already set! type = 0

### ISSUE THREAD

**Issue by BenettChen** [alibaba/transmittable-thread-local#550]
我在使用JavaAgent形式的时候，出现这个异常

```java
Exception in thread "main" java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
  at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalStateException: TTL logger implementation type is already set! type = 0
  at com.alibaba.ttl.threadpool.agent.internal.logging.Logger.setLoggerImplType(Logger.java:22)
  at com.alibaba.ttl.threadpool.agent.TtlAgent.premain(TtlAgent.java:129)
```

JVM配置如下：
`-Xmx3g -XX:+UseG1GC -XX:MaxGCPauseMillis=300 -javaagent:/opt/service/zhaopin_scf_zpjob/config/lib/transmittable-thread-local-2.14.0.jar`

Maven依赖包：

```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>transmittable-thread-local</artifactId>
    <version>2.14.0</version>
</dependency>
```

**Comment by BenettChen** [comment]
刚我也和中间件团队一起排查了这个问题，发现是中间件团队在某些情况下也会使用TTL，应该中间件团队的TTL和业务程序中TTL冲突导致，我把中间件的TTL关掉调，后面部署就没问题了。就当一个问题记录吧，后面有人遇到这个异常，先考虑下自己的环境问题，多一个排查方向。
