### ISSUE TITLE
2.14.3版本在JDK 21中遇到了类转换异常问题，TTL是否支持JDK 21？

### ISSUE THREAD

**Issue by brucelwl** [alibaba/transmittable-thread-local#555]
2.14.3版本是不是还不支持JDK21??

**Comment by wuwen5** [comment]
从目前的CI构建中看，是覆盖了JDK21的，覆盖了JDK21环境的测试。
建议你反馈你在jdk21环境中你遇到了什么问题，提供相关有效的信息。

**Comment by brucelwl** [comment]
@wuwen5 异常信息如下
```
2023-09-28 10:53:34.927 SEVERE [main] TtlTransformer: Fail to transform class sun/net/httpserver/ServerImpl$ReqRspTimeoutTask, cause: java.lang.NullPointerException: Cannot read field "string" because "utf" is null
java.lang.NullPointerException: Cannot read field "string" because "utf" is null
	at com.alibaba.ttl.threadpool.agent.internal.javassist.bytecode.ConstPool.getUtf8Info(ConstPool.java:675)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.bytecode.MethodParametersAttribute.copy(MethodParametersAttribute.java:90)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.bytecode.AttributeInfo.copyAll(AttributeInfo.java:249)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.bytecode.MethodInfo.compact(MethodInfo.java:157)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.bytecode.ClassFile.compact(ClassFile.java:242)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtClassType.toBytecode(CtClassType.java:1583)
	at com.alibaba.ttl.threadpool.agent.internal.javassist.CtClass.toBytecode(CtClass.java:1519)
	at com.alibaba.ttl.threadpool.agent.TtlTransformer.transform(TtlTransformer.java:81)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1118)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:182)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:741)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:665)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
	at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
	at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(HttpServer.java:152)
	at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(HttpServer.java:126)
	at io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:144)
	at io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:165)
```

**Comment by wuwen5** [comment]
应该是`javassist`在处理 `sun/net/httpserver/ServerImpl$ReqRspTimeoutTask` 字节码的时候出现了问题，相关issue已提交到`javassist` https://github.com/jboss-javassist/javassist/issues/462

**Comment by wuwen5** [comment]
知道怎么回事了，问题出现在内部类的字节码发生了细微变化，在java8之后，当使用 `-parameters` 选项编译Java代码时，编译器会将方法参数的名称存储在类文件的调试信息中。这样，当你使用调试器来调试程序时，可以看到方法的参数名称而不仅仅是它们的类型。

class信息如下 (当未使用-parameters编译时，不会携带`MethodParameters`)
```
public void test(int, java.lang.String);
    descriptor: (ILjava/lang/String;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=0, locals=3, args_size=3
         0: return
      LineNumberTable:
        line 4: 0
    MethodParameters:
      Name                           Flags
      i
      s
```

默认在jdk中的class应该是没有携带`-parameters`编译的，所以默认不会携带`MethodParameters`，目前查看class也是这样。
但是在Java21中编译内部类时，即使没携带`-parameters`编译时，构造函数会携带以下信息，这与其他版本jdk字节码不一致，这也是不合理和非预期的地方。
```
MethodParameters:
      Name                           Flags
      <no name>                      final mandated
```

当使用`-parameters`编译时，构造函数部分如下，这与jdk8以上版本都一致
```
MethodParameters:
      Name                           Flags
      this$0                         final mandated
```


所以，总结为，java21编译的内部类字节码发生了变化，引起的兼容性问题。

`javassist`在解析java21编译的内部类字节码时，在对`MethodParameters`字节码的解析时无法从常量池中获取字符信息。
大致可以这么理解，字节码告诉了构造方法有一个参数，对应常量池的下标为0，常量池下标从1开始，即无法从常量池获取字符串定义。

**Comment by brucelwl** [comment]
@wuwen5 是不是意味着即使用jdk8 在添加`-parameters`参数的情况下,也会触发这个异常?

**Comment by wuwen5** [comment]
> @wuwen5 是不是意味着即使用jdk8 在添加`-parameters`参数的情况下,也会触发这个异常?

不会

添加`-parameters`参数时，无论是java21还是java8都会正确符合预期的带上`MethodParameters `信息，此时`javassist`能正常解析。

现在问题是没使用`-parameters`参数时，预期是不带`MethodParameters `，但是java21却在内部类的构造方法中带了，而且还是带的个错误的。

通俗点讲，就是不加这个参数，字节码不会告诉你有参数名称信息，加了这个参数就会告诉你有参数名称，且参数名称是xxx，
但是java21在编译内部类的时候，没带这个参数，却告诉你，有参数名称，参数名称是`<no name>`.
(怀疑是java21的问题)

**Comment by brucelwl** [comment]
@wuwen5 目前看来只能在`javassist`层面兼容这个问题, 或者反馈给JDK确认是否是预期之类的更改

**Comment by wuwen5** [comment]
先记录下可能与之相关的信息

https://github.com/openjdk/jdk/pull/13167
https://github.com/openjdk/jdk/pull/9862
https://bugs.openjdk.org/browse/JDK-8304837

**Comment by wuwen5** [comment]
进一步研究发现，影响范围为java21编译出来的非静态的内部类

非静态内部类, 包含`MethodParameters` `<no name>`
```
Java21InnerClassWithoutParameters$InnerClass(Java21InnerClassWithoutParameters);
    descriptor: (LJava21InnerClassWithoutParameters;)V
    flags: (0x0000)
    Code:
      stack=1, locals=2, args_size=2
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 2: 0
    MethodParameters:
      Name                           Flags
      <no name>                      final mandated
```

静态内部类，不含`MethodParameters`
```
Java21InnerClassWithoutParameters$StaticInnerClass();
    descriptor: ()V
    flags: (0x0000)
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 7: 0
```

**Comment by liach** [comment]
虚拟机规范允许MethodParameters里面项目名称指向0，表示参数没有名称。javaassist没有考虑这种情况，因为之前好像没有编译器在里面放0所以实际使用时javaassist没出过错。你可以编译个带Optional参数的enum：
```java
enum TestEnum {
  INSTANCE(Optional.of("A"));
  TestEnum(Optional<String> opt) {}
}
```
也会受影响，因为编译器加了name ordinal两个参数，类似inner class有个outer this参数。
这个改动主要是为了修这个例子里面的一个bug：本来`constructor.getParameters()[2].getParameterizedType()`返回是`Optional.class`，这个改动后因为编译器加信息，会返回代表`Optional<String>`的`Type`

**Comment by wuwen5** [comment]
当前已发布的`javassist-3.30.1-GA`已经修复了这个问题，但是由于合入了其他修改，编译的字节码升级到了`JDK-11`，因此这个版本我们暂时还不能直接升级，需等待下个版本发布.

- https://github.com/jboss-javassist/javassist/pull/473 
- https://github.com/jboss-javassist/javassist/pull/470

**Comment by oldratlee** [comment]
> 当前已发布的`javassist-3.30.1-GA`已经修复了这个问题，但是由于合入了其他修改，编译的字节码升级到了`JDK-11`

@wuwen5 

我也发现了`javassist-3.30.1-GA`升级到了`Java 11` 😰
可以推进让`javassist`新版别放弃`Java 8`的支持？😄

**Comment by oldratlee** [comment]
@brucelwl @wuwen5 @liach 

- reproduce the problem at commit 06728d2ca538460a571c3ee8018683e6487098d8
  - more info see the related **_failed_** CI jobs
- fix the problem at commit de6be19343c07cfbad2f06f7900693f74443462d
- released in `v2.14.5`:
  https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.14.5
