### ISSUE TITLE
graalvm TraversingBlockingQueue ArrayStoreException

### ISSUE THREAD

**Issue by imhun** [alibaba/transmittable-thread-local#635]
ttl 2.14.5, use agent
graalvm-js:23.0
when run js script,
Occasionally the following error occurs:

Caused by: org.graalvm.polyglot.PolyglotException: java.lang.ArrayStoreException: com.alibaba.ttl.TtlRunnable
	at java.base/java.util.concurrent.LinkedBlockingDeque.toArray(LinkedBlockingDeque.java:963)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.TraversingBlockingQueue.toArray(TraversingBlockingQueue.java:214)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue.getQueuedTargets(BackgroundCompileQueue.java:216)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.flushCompileQueue(GraalRuntimeSupport.java:275)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureClosed(PolyglotEngineImpl.java:1259)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.closeAndMaybeWait(PolyglotContextImpl.java:1643)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.close(PolyglotContextImpl.java:1565)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.close(PolyglotContextDispatch.java:73)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.close(Context.java:835)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.close(Context.java:861)
	at com.byteplan.data.yunhua.script.JavaScriptHelper.eval(JavaScriptHelper.java:160)

**Comment by oldratlee** [comment]
@imhun Please give a runnable reproducible demo

**Comment by oldratlee** [comment]
历史排查问题 issue，先 close 了
