### ISSUE TITLE
DistributedTracerUseDemo 空指针异常

### ISSUE THREAD

**Issue by wychenlong** [alibaba/transmittable-thread-local#71]
rpcInvokeIn 发起了两个线程异步执行任务调用，任务没有执行完成之前就执行了上下文清理

**Comment by oldratlee** [comment]
@wychenlong 麻烦给一下信息，如 异常栈，方便我确定问题

**Comment by wychenlong** [comment]
DEBUG: Increase reference counter(1) for traceId traceId_XXXYYY in thread main
Do Rpc invocation to server server 1 with {traceId=traceId_XXXYYY, spanId=1.1.1}
DEBUG: Decrease reference counter(0) for traceId traceId_XXXYYY in thread main
DEBUG: Clear traceId2LeafSpanIdInfo for traceId traceId_XXXYYY in thread main
java.lang.NullPointerException
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo.increaseSpanIdRefCounter(DistributedTracerUseDemo.java:87)
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo$2.beforeExecute(DistributedTracerUseDemo.java:67)
	at com.alibaba.ttl.TransmittableThreadLocal.doExecuteCallback(TransmittableThreadLocal.java:188)
	at com.alibaba.ttl.TransmittableThreadLocal.backupAndSetToCopied(TransmittableThreadLocal.java:152)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
java.lang.NullPointerException
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo.decreaseSpanIdRefCounter(DistributedTracerUseDemo.java:97)
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo$2.afterExecute(DistributedTracerUseDemo.java:72)
	at com.alibaba.ttl.TransmittableThreadLocal.doExecuteCallback(TransmittableThreadLocal.java:190)
	at com.alibaba.ttl.TransmittableThreadLocal.restoreBackup(TransmittableThreadLocal.java:159)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Exception in thread "Thread-by-new" java.lang.NullPointerException
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo.increaseLeafSpanCurrentAndReturn(DistributedTracerUseDemo.java:114)
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo.invokeServerWithRpc(DistributedTracerUseDemo.java:185)
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo.syncMethod_ByNewThread(DistributedTracerUseDemo.java:175)
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo$4.run(DistributedTracerUseDemo.java:163)
	at java.lang.Thread.run(Thread.java:662)

Process finished with exit code 0


JDK1.6_45

**Comment by wychenlong** [comment]
increaseSpanIdRefCounter();

        ////////////////////////////////////////////////
        // Biz Code
        ////////////////////////////////////////////////
        syncMethod();

        ////////////////////////////////////////////////
        // DistributedTracer Framework Code
        ////////////////////////////////////////////////
        decreaseSpanIdRefCounter();

 syncMethod();异步执行的逻辑，decreaseSpanIdRefCounter先与异步的线程执行

**Comment by oldratlee** [comment]
从你的日志

```java
java.lang.NullPointerException
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo.increaseSpanIdRefCounter(DistributedTracerUseDemo.java:87)
	at com.jdjr.study.sgm.sgm.DistributedTracerUseDemo$2.beforeExecute(DistributedTracerUseDemo.java:67)
	at com.alibaba.ttl.TransmittableThreadLocal.doExecuteCallback(TransmittableThreadLocal.java:188)
```

这个你的改过的`Demo`代码`com.jdjr.study.sgm.sgm.DistributedTracerUseDemo.increaseSpanIdRefCounter`/`com.jdjr.study.sgm.sgm.DistributedTracerUseDemo$2.beforeExecute`，可能是你Demo的实现问题。

要具体排查需要你给出你的`Demo`的完整代码。

@wychenlong 建议你把你的整体工程提交到`GitHub`上，这样方便复现问题且有相应的信息来解决。
